const books = [
  {
    title: "12 Rules For Life",
    chapter: "3",
    author: "Jordan B. Peterson",
    genre: "self-help",
    picture: 'src/img/12.jpg',
    summary: ' Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolor error rerum adipisci officia nobis maiores porro ',
  },
  {
    title: "Basic Economics",
    chapter: "5",
    author: "Thomas Sowell",
    genre: "Economics",
    picture: '',
    summary: '',
  },
  {
    title: "Laws of Human Nature",
    chapter: "6",
    author: "Robert greene",
    genre: "psycology",
    picture: '',
    summary: '',
  },
  {
    title: "Sapiens",
    chapter: "4",
    author: "Yuval Harrari",
    genre: "history",
    picture: '',
    summary: '',
  },
  {
    title: "The Black Swan",
    chapter: "6",
    author: "Nassim Taleb",
    genre: "psycology",
    picture: '',
    summary: '',
  },
  {
    title: "Deep Work",
    chapter: "3",
    author: "Cal Newport",
    genre: "self-help",
    picture: '',
    summary: '',
  },
  {
    title: "The Psychology of Money",
    chapter: 14,
    author: "morgan housel",
    genre: "finance",
    picture: '',
    summary: '',
  },
  {
    title: "americana",
    chapter: 4,
    author: "bhu srinivasan",
    genre: "history",
    picture: '',
    summary: '',
  },
  {
    title: "the selfish gene",
    chapter: 5,
    author: "richard dawkins",
    genre: "science",
    picture: '',
    summary: '',
  }
]

